#!/usr/bin/env python3
"""
Release verification for the public reproducibility package.

Purpose: check that the repository is internally consistent and that its public
reproduction path actually runs -- NOT to force scientific results to match.
Nothing here edits a released CSV, and no expected value is hard-coded beyond
what is already published in ``aggregate_data/`` and ``figure_data/``.

Two levels are distinguished throughout:

  PUBLIC reproduction   -- what anyone can run from this repository alone:
                           the synthetic smoke test, figure regeneration from
                           the released datapoints, and arithmetic consistency
                           of the released aggregate tables.
  OPERATOR reproduction -- re-running the analysis on a platform-native NAC
                           export (``--operator-exports DIR``). The eight study
                           exports are restricted, so the published per-estate
                           values can only be regenerated by an authorised
                           operator holding them; on anyone else's export the
                           scripts produce that estate's own numbers, which are
                           not expected to match the manuscript.

Usage
-----
    python3 verify_release.py                      # public checks only
    python3 verify_release.py --operator-exports DIR [--cpe-dictionary PATH]
    python3 verify_release.py --keep out/verify    # keep generated outputs

Exit status 0 if no check FAILed; 1 otherwise. "NOT TESTED" and
"NOT REPRODUCIBLE" are reported, never counted as PASS.
"""
from __future__ import annotations

import argparse
import csv
import filecmp
import os
import re
import shutil
import subprocess
import sys
import tempfile
from typing import Dict, List, Optional, Sequence, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))        # reproducibility/
ROOT = os.path.dirname(HERE)                             # repository root
ANALYSIS = os.path.join(HERE, "analysis")
PY = sys.executable

REQUIRED_FILES = [
    "README.md", "LICENSE", "CITATION.cff", "CODE_AVAILABILITY.md", "DATA_AVAILABILITY.md",
    ".gitignore",
    "reproducibility/README.md", "reproducibility/LICENSE",
    "reproducibility/environment/requirements.txt",
    "reproducibility/docs/reproduction.md",
    "reproducibility/reproduce_figures.py",
    "reproducibility/analysis/common.py",
    "reproducibility/analysis/estate_structure.py",
    "reproducibility/analysis/lexical_features.py",
    "reproducibility/analysis/cpe_route.py",
    "reproducibility/example_data/synthetic_estate.csv",
    "reproducibility/example_data/cpe/synthetic_cpe_dictionary.xml",
    "reproducibility/example_data/cpe/synthetic_advisory_corpus.csv",
    "reproducibility/aggregate_data/table2_version_coverage.csv",
    "reproducibility/aggregate_data/estate_structure.csv",
    "reproducibility/aggregate_data/table4_version_spread.csv",
    "reproducibility/aggregate_data/table5_fanout_distribution.csv",
    "reproducibility/aggregate_data/table6_lexical_features.csv",
    "reproducibility/aggregate_data/table7_cpe_route.csv",
    "reproducibility/figure_data/figure1_fanout.csv",
    "reproducibility/figure_data/figure6_speedup.csv",
    "reproducibility/figure_data/figure7_latency.csv",
]

# Files that must never be present in a public checkout.
FORBIDDEN_EXT = (".env", ".pem", ".key", ".p12", ".pfx", ".pth", ".pt", ".onnx", ".ckpt",
                 ".safetensors", ".xlsx", ".xls", ".db", ".sqlite", ".sqlite3", ".dump")
FORBIDDEN_TEXT = re.compile(r"(/home/|/Users/|[A-Za-z]:\\\\Users\\\\|BEGIN (RSA |OPENSSH )?PRIVATE KEY)")
TEXT_EXT = (".py", ".md", ".csv", ".txt", ".cff", ".tex", ".bib", ".cls", ".xml", ".yml", ".yaml", ".toml")

# Released aggregate CSVs: required columns, and the script that produces them.
AGGREGATE_SCHEMA: Dict[str, Tuple[str, List[str]]] = {
    "table2_version_coverage.csv": ("estate_structure.py", ["estate", "endpoints", "live_rows", "no_version_pct"]),
    "estate_structure.csv": ("estate_structure.py", ["estate", "endpoints", "live_rows", "no_version_pct", "R_scannable",
                                                      "U_items", "G_products", "rho_item", "rho_group", "reduction_pct"]),
    "table4_version_spread.csv": ("estate_structure.py", ["estate", "products_G", "multi_version_count", "multi_version_pct", "widest_spread"]),
    "table5_fanout_distribution.csv": ("estate_structure.py", ["estate", "p50", "p90", "p99", "max", "top1pct", "top5pct", "top10pct", "singletons_pct"]),
    "table6_lexical_features.csv": ("lexical_features.py", ["feature", "example_fragment", "share_pct"]),
    "table7_cpe_route.csv": ("cpe_route.py", ["stage", "by_name_pct", "by_row_pct"]),
}
TABLE_OF_FILE = {"table2_version_coverage.csv": "Table 2", "estate_structure.csv": "Table 3",
                 "table4_version_spread.csv": "Table 4", "table5_fanout_distribution.csv": "Table 5",
                 "table6_lexical_features.csv": "Table 6", "table7_cpe_route.csv": "Table 7"}


class Report:
    def __init__(self) -> None:
        self.lines: List[Tuple[str, str, str]] = []

    def add(self, name: str, status: str, detail: str = "") -> None:
        self.lines.append((name, status, detail))
        print(f"{name:.<58s} {status}" + (f"   ({detail})" if detail else ""))

    @property
    def failed(self) -> bool:
        return any(s.startswith("FAIL") for _, s, _ in self.lines)


def read_csv(path: str) -> Tuple[List[str], List[List[str]]]:
    with open(path, newline="", encoding="utf-8") as f:
        rows = [r for r in csv.reader(f) if r and r[0].strip() and not r[0].lstrip().startswith("#")]
    return [h.strip() for h in rows[0]], rows[1:]


def run(cmd: Sequence[str], cwd: str) -> subprocess.CompletedProcess:
    return subprocess.run(list(cmd), cwd=cwd, capture_output=True, text=True)


def close(a: float, b: float, tol: float) -> bool:
    return abs(a - b) <= tol + 1e-9


# ------------------------------------------------------------------ checks --
def check_required_files(rep: Report) -> None:
    missing = [p for p in REQUIRED_FILES if not os.path.exists(os.path.join(ROOT, p))]
    rep.add("Required public files", "PASS" if not missing else "FAIL", ", ".join(missing))


def check_forbidden_content(rep: Report) -> None:
    bad_files, bad_text = [], []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in (".git", "__pycache__", "out", ".venv", "venv")]
        for fn in filenames:
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, ROOT)
            if fn.lower().endswith(FORBIDDEN_EXT) or fn == ".env" or fn.startswith(".env."):
                bad_files.append(rel)
            if fn.lower().endswith(TEXT_EXT) and path != os.path.abspath(__file__):
                try:
                    with open(path, encoding="utf-8", errors="replace") as f:
                        for i, line in enumerate(f, 1):
                            if FORBIDDEN_TEXT.search(line):
                                bad_text.append(f"{rel}:{i}")
                                break
                except OSError:
                    pass
    rep.add("No forbidden file types in checkout", "PASS" if not bad_files else "FAIL", ", ".join(bad_files))
    rep.add("No private paths / key material in text files", "PASS" if not bad_text else "FAIL", ", ".join(bad_text))


def check_py_compile(rep: Report) -> None:
    files = [os.path.join(ANALYSIS, f) for f in ("common.py", "estate_structure.py", "lexical_features.py", "cpe_route.py")]
    files.append(os.path.join(HERE, "reproduce_figures.py"))
    r = run([PY, "-m", "py_compile", *files], HERE)
    rep.add("Python sources compile", "PASS" if r.returncode == 0 else "FAIL", r.stderr.strip()[-200:])
    shutil.rmtree(os.path.join(ANALYSIS, "__pycache__"), ignore_errors=True)


def run_synthetic(out_dir: str) -> Dict[str, subprocess.CompletedProcess]:
    ex = os.path.join(HERE, "example_data")
    cpe = os.path.join(ex, "cpe")
    return {
        "estate_structure.py": run([PY, os.path.join(ANALYSIS, "estate_structure.py"), "--dir", ex, "--out", out_dir], HERE),
        "lexical_features.py": run([PY, os.path.join(ANALYSIS, "lexical_features.py"), "--dir", ex, "--out", out_dir], HERE),
        "cpe_route.py": run([PY, os.path.join(ANALYSIS, "cpe_route.py"), "--dir", ex,
                             "--cpe-dictionary", os.path.join(cpe, "synthetic_cpe_dictionary.xml"),
                             "--advisory-corpus", os.path.join(cpe, "synthetic_advisory_corpus.csv"),
                             "--out", out_dir], HERE),
    }


def check_synthetic_pipeline(rep: Report, work: str) -> None:
    out1 = os.path.join(work, "synthetic_run1")
    out2 = os.path.join(work, "synthetic_run2")
    res1 = run_synthetic(out1)
    res2 = run_synthetic(out2)
    for script, r in res1.items():
        ok = r.returncode == 0 and "excluded (unreadable)" not in r.stdout
        rep.add(f"Synthetic smoke test: {script}", "PASS" if ok else "FAIL",
                "" if ok else (r.stderr.strip() or r.stdout.strip())[-200:])
    # schema of produced outputs vs released aggregate CSVs
    for fname, (script, required_cols) in AGGREGATE_SCHEMA.items():
        produced = os.path.join(out1, fname)
        table = TABLE_OF_FILE[fname]
        if not os.path.exists(produced):
            rep.add(f"{table} pipeline output (synthetic input)", "FAIL", f"{fname} not written")
            continue
        header, rows = read_csv(produced)
        missing = [c for c in required_cols if c not in header]
        ok = not missing and len(rows) > 0
        rep.add(f"{table} pipeline output (synthetic input)", "PASS" if ok else "FAIL",
                f"missing columns {missing}" if missing else ("no rows" if not rows else ""))
    fig1 = os.path.join(out1, "figure1_fanout.csv")
    if os.path.exists(fig1):
        header, rows = read_csv(fig1)
        ok = header == ["estate", "items_consumed_pct", "rows_covered_pct"] and rows and rows[-1][1] == "100.0"
        rep.add("Figure 1 datapoints (synthetic input)", "PASS" if ok else "FAIL")
    else:
        rep.add("Figure 1 datapoints (synthetic input)", "FAIL", "figure1_fanout.csv not written")
    # determinism: two runs must be byte-identical
    diffs = []
    for fname in sorted(os.listdir(out1)):
        a, b = os.path.join(out1, fname), os.path.join(out2, fname)
        if not os.path.exists(b) or not filecmp.cmp(a, b, shallow=False):
            diffs.append(fname)
    rep.add("Synthetic outputs deterministic (2 runs)", "PASS" if not diffs else "FAIL", ", ".join(diffs))


def check_released_schema(rep: Report) -> None:
    for fname, (script, required_cols) in AGGREGATE_SCHEMA.items():
        path = os.path.join(HERE, "aggregate_data", fname)
        header, rows = read_csv(path)
        missing = [c for c in required_cols if c not in header]
        rep.add(f"{TABLE_OF_FILE[fname]} released CSV schema", "PASS" if not missing and rows else "FAIL",
                f"missing {missing}" if missing else "")


def check_released_consistency(rep: Report) -> None:
    """Arithmetic consistency of the released tables with each other (no external truth)."""
    agg = os.path.join(HERE, "aggregate_data")
    problems: List[str] = []

    h, rows = read_csv(os.path.join(agg, "estate_structure.csv"))
    col = {c: i for i, c in enumerate(h)}
    per_estate = [r for r in rows if r[col["estate"]] != "Pooled"]
    pooled = next(r for r in rows if r[col["estate"]] == "Pooled")
    for r in rows:
        R, U, G = float(r[col["R_scannable"]]), float(r[col["U_items"]]), float(r[col["G_products"]])
        if not close(R / U, float(r[col["rho_item"]]), 0.05):
            problems.append(f"T3 {r[0]} rho_item")
        if not close(U / G, float(r[col["rho_group"]]), 0.005):
            problems.append(f"T3 {r[0]} rho_group")
        if not close(100 * (1 - U / R), float(r[col["reduction_pct"]]), 0.05):
            problems.append(f"T3 {r[0]} reduction_pct")
    for c in ("endpoints", "live_rows", "R_scannable", "U_items", "G_products"):
        if sum(int(r[col[c]]) for r in per_estate) != int(pooled[col[c]]):
            problems.append(f"T3 pooled {c} != sum of estates")
    rep.add("Table 3 released values arithmetically consistent", "PASS" if not problems else "FAIL", "; ".join(problems))

    problems = []
    h2, rows2 = read_csv(os.path.join(agg, "table2_version_coverage.csv"))
    c2 = {c: i for i, c in enumerate(h2)}
    t2 = {r[c2["estate"]]: r for r in rows2}
    for r in rows:
        e = r[col["estate"]]
        if e not in t2:
            problems.append(f"T2 missing {e}")
            continue
        for c in ("endpoints", "live_rows", "no_version_pct"):
            if t2[e][c2[c]] != r[col[c]]:
                problems.append(f"T2/T3 {e} {c} differ")
    rep.add("Table 2 agrees with Table 3 (shared columns)", "PASS" if not problems else "FAIL", "; ".join(problems))

    problems = []
    h4, rows4 = read_csv(os.path.join(agg, "table4_version_spread.csv"))
    c4 = {c: i for i, c in enumerate(h4)}
    t3G = {r[col["estate"]]: int(r[col["G_products"]]) for r in per_estate}
    for r in rows4:
        e = r[c4["estate"]]
        if int(r[c4["products_G"]]) != t3G.get(e):
            problems.append(f"T4 {e} G != T3 G")
        if not close(100 * int(r[c4["multi_version_count"]]) / int(r[c4["products_G"]]), float(r[c4["multi_version_pct"]]), 0.05):
            problems.append(f"T4 {e} multi_version_pct")
    rep.add("Table 4 agrees with Table 3 and is self-consistent", "PASS" if not problems else "FAIL", "; ".join(problems))

    problems = []
    h5, rows5 = read_csv(os.path.join(agg, "table5_fanout_distribution.csv"))
    c5 = {c: i for i, c in enumerate(h5)}
    t5 = {r[c5["estate"]]: r for r in rows5}
    hf, rowsf = read_csv(os.path.join(HERE, "figure_data", "figure1_fanout.csv"))
    curves: Dict[str, Dict[float, float]] = {}
    for e, x, y in rowsf:
        curves.setdefault(e, {})[float(x)] = float(y)
    for e, pts in curves.items():
        if e not in t5:
            problems.append(f"F1 {e} not in T5")
            continue
        # estate_structure.py writes exact points at the Table 5 head-share
        # positions (k = round(n*f) items, so x is within one item of 1/5/10 %);
        # the nearest datapoint to each must carry the Table 5 value.
        for x, c in ((1.0, "top1pct"), (5.0, "top5pct"), (10.0, "top10pct")):
            nearest = min(pts, key=lambda v: abs(v - x))
            if abs(nearest - x) > 0.6:
                problems.append(f"F1 {e} has no datapoint near {x:g}% (nearest {nearest:g}%)")
            elif not close(pts[nearest], float(t5[e][c5[c]]), 0.05):
                problems.append(f"F1 {e} @{nearest:g}% = {pts[nearest]:g} != T5 {c} {t5[e][c5[c]]}")
        if pts.get(0.0) != 0.0 or pts.get(100.0) != 100.0:
            problems.append(f"F1 {e} endpoints not (0,0)/(100,100)")
    rep.add("Figure 1 datapoints agree with Table 5 head shares", "PASS" if not problems else "FAIL", "; ".join(problems))


def check_figures(rep: Report, work: str) -> None:
    out = os.path.join(work, "figures")
    r = run([PY, os.path.join(HERE, "reproduce_figures.py"), "--out", out], HERE)
    if r.returncode != 0:
        rep.add("Figure 1 reproduction (released datapoints)", "FAIL", r.stderr.strip()[-200:])
        rep.add("Figure 6 reproduction (released datapoints)", "FAIL", "reproduce_figures.py failed")
    else:
        for n, stem in (("1", "figure1_fanout"), ("6", "figure6_speedup")):
            ok = all(os.path.getsize(os.path.join(out, f"{stem}.{ext}")) > 0 for ext in ("pdf", "png")
                     if os.path.exists(os.path.join(out, f"{stem}.{ext}")))
            ok = ok and os.path.exists(os.path.join(out, f"{stem}.pdf"))
            rep.add(f"Figure {n} reproduction (released datapoints)", "PASS" if ok else "FAIL")
    rep.add("Figure 7 reproduction", "NOT REPRODUCIBLE",
            "panel (a) needs the 200 unreleased latencies; panel (b) medians drawn without spread as figure7b_partial")


def check_operator(rep: Report, exports: str, cpe_dict: Optional[str], work: str) -> None:
    """Re-run the analysis on an operator's own exports and compare with the released tables."""
    out = os.path.join(work, "operator")
    os.makedirs(out, exist_ok=True)
    runs = {
        "estate_structure.py": run([PY, os.path.join(ANALYSIS, "estate_structure.py"), "--dir", exports, "--out", out,
                                    "--curve-estates", "E3,E6,E8,E7"], HERE),
        "lexical_features.py": run([PY, os.path.join(ANALYSIS, "lexical_features.py"), "--dir", exports, "--out", out], HERE),
    }
    if cpe_dict:
        runs["cpe_route.py"] = run([PY, os.path.join(ANALYSIS, "cpe_route.py"), "--dir", exports,
                                    "--cpe-dictionary", cpe_dict, "--out", out], HERE)
    for script, r in runs.items():
        rep.add(f"Operator run: {script}", "PASS" if r.returncode == 0 else "FAIL", (r.stderr.strip())[-200:])
    for fname, (script, cols) in AGGREGATE_SCHEMA.items():
        table = TABLE_OF_FILE[fname]
        produced = os.path.join(out, fname)
        if not os.path.exists(produced):
            rep.add(f"{table} operator reproduction vs released", "NOT TESTED", "no output" + ("" if cpe_dict or script != "cpe_route.py" else "; --cpe-dictionary not given"))
            continue
        hp, rp = read_csv(produced)
        hr, rr = read_csv(os.path.join(HERE, "aggregate_data", fname))
        keycol = hr[0]
        prod = {r[hp.index(keycol)]: r for r in rp}
        mism = []
        for r in rr:
            key = r[0]
            if key not in prod:
                mism.append(f"{key} missing")
                continue
            for c in cols[1:]:
                if c not in hp:
                    mism.append(f"{key}.{c} absent")
                    continue
                a, b = r[hr.index(c)], prod[key][hp.index(c)]
                try:
                    tol = 0.05 if "." in a else 0.5
                    if not close(float(a), float(b), tol):
                        mism.append(f"{key}.{c} {a}!={b}")
                except ValueError:
                    if a != b:
                        mism.append(f"{key}.{c} {a}!={b}")
        if fname == "table7_cpe_route.csv" and len(rp) < len(rr):
            rep.add(f"{table} operator reproduction vs released", "NOT TESTED",
                    "stage 2 needs --advisory-corpus; tiers compared only" if not mism else "; ".join(mism[:6]))
            continue
        rep.add(f"{table} operator reproduction vs released", "PASS" if not mism else "FAIL", "; ".join(mism[:6]))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--operator-exports", metavar="DIR", help="directory of platform-native NAC exports (operator reproduction)")
    ap.add_argument("--cpe-dictionary", metavar="PATH", help="official CPE dictionary for Table 7 in operator mode")
    ap.add_argument("--keep", metavar="DIR", help="keep generated outputs under DIR instead of a temp directory")
    args = ap.parse_args()

    work = args.keep or tempfile.mkdtemp(prefix="verify_release_")
    os.makedirs(work, exist_ok=True)
    rep = Report()
    print(f"repository: {ROOT}\nwork dir:   {work}\n")
    check_required_files(rep)
    check_forbidden_content(rep)
    check_py_compile(rep)
    check_released_schema(rep)
    check_released_consistency(rep)
    check_synthetic_pipeline(rep, work)
    check_figures(rep, work)
    for t in ("Table 2", "Table 3", "Table 4", "Table 5", "Table 6"):
        rep.add(f"{t} published values (restricted exports)",
                "NOT TESTED" if not args.operator_exports else "see operator section",
                "" if args.operator_exports else "requires the eight study exports, which are restricted")
    rep.add("Table 7 published values",
            "NOT REPRODUCIBLE",
            "restricted exports, the 3 Aug 2026 production dictionary state and the measurement code are unavailable; pipeline exercised on a synthetic dictionary only")
    if args.operator_exports:
        print("\n-- operator reproduction --")
        check_operator(rep, args.operator_exports, args.cpe_dictionary, work)
    shutil.rmtree(os.path.join(ANALYSIS, "__pycache__"), ignore_errors=True)
    if not args.keep:
        shutil.rmtree(work, ignore_errors=True)
    n_fail = sum(1 for _, s, _ in rep.lines if s.startswith("FAIL"))
    print(f"\n{'FAILED' if n_fail else 'OK'}: {n_fail} check(s) failed, "
          f"{sum(1 for _, s, _ in rep.lines if s == 'PASS')} passed, "
          f"{sum(1 for _, s, _ in rep.lines if s not in ('PASS',) and not s.startswith('FAIL'))} not tested / not reproducible")
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
